### ISSUE TITLE
add templated Service annotations

### ISSUE THREAD

**Issue by TheCase** [1Password/connect-helm-charts#106]
### Summary
add templated metadata.annotations to the Service

### Use cases
useful for anyone that uses Service annotations to control things like load balancer controllers, etc.

### Proposed solution 
like what has been done for [metadata.labels](https://github.com/1Password/connect-helm-charts/blob/main/charts/connect/templates/service.yaml#L6) in the Service template, but for annotations 

### Is there a workaround to accomplish this today?
manually add to the manifest, post deploy

**Comment by dkamenov-fitted** [comment]
@jpcoenen, is this something that can be merged?
