### ISSUE TITLE
Follow helm and kubernetes standards for labels

### ISSUE THREAD

**Issue by nesl247** [1Password/connect-helm-charts#11]
Please follow helm and kubernetes standards for labels. See https://helm.sh/docs/chart_best_practices/labels/.

**Comment by florisvdg** [comment]
Thank you for addressing. https://github.com/1Password/connect-helm-charts/pull/21 will add these labels for all deployments, services, and secrets.

And what do you think, considering Helm's recommendation on not overdoing labels and listing the following as a condition:
> It is useful to expose to operators for the purpose of querying the system.

Would you say these labels also belong on the CRD definition and RBAC resources?

**Comment by nesl247** [comment]
I'm not sure what the standard is for CRDs, I would check out existing helm charts. I would definitely add the labels to the RBAC resources though.

**Comment by nesl247** [comment]
I'm not sure what the standard is for CRDs, I would check out existing helm charts. I would definitely add the labels to the RBAC resources though.
