### ISSUE TITLE
Use `.Release.Namespace` instead of custom namespace value

### ISSUE THREAD

**Issue by nesl247** [1Password/connect-helm-charts#13]
You should use `.Release.Namespace` instead of a custom variable. Generally you would want to avoid using the `default` namespace, but helm also has standard variables for a lot of stuff, the namespace being one of them.

https://helm.sh/docs/chart_template_guide/builtin_objects/

**Comment by florisvdg** [comment]
You're absolutely right. We'll address this in the next release. Thanks!
