### ISSUE TITLE
More frequently patched images for onepassword-connect

### ISSUE THREAD

**Issue by pjbgf** [1Password/connect-helm-charts#131]
Would it be possible for the `connect-api` images to be patched more frequently, or a distroless version of it to be made available, so that its supply chain CVEs are kept to a minimum? Currently trivy is detecting 174 CVEs on the latest version:
![image](https://user-images.githubusercontent.com/5452977/207318025-c1c8bd73-db52-47a9-8b66-796e2d3b3d1a.png)

The latest tag was updated [3 months ago](https://hub.docker.com/r/1password/connect-api/tags): 
![image](https://user-images.githubusercontent.com/5452977/207318646-aa61ba05-b731-4d1b-91f6-e5f9a2426006.png)

**Comment by jpcoenen** [comment]
Hey @pjbgf! I see your concern. Thanks for your suggestion, we're going to look into publishing distroless images.

**Comment by jillianwilson** [comment]
@pjbgf Distroless images are now available for Connect!

**Comment by pjbgf** [comment]
@jillianwilson thank you for seeing this through and the follow-up. :bow:
