### ISSUE TITLE
Wrongly generated serviceName when tls is enabled

### ISSUE THREAD

**Issue by Altiire** [1Password/connect-helm-charts#140]
### Your environment

Chart Version: latest

Helm Version: 3.11.2

Kubernetes Version: 1.25.4

## What happened?

`onepassword-connect-https` service does not exist as the service template generate `onepassword-connect` service using http and https if tls is enabled

## What did you expect to happen?

`onepassword-connect` service should be used by the ingress when tls is enabled

## Steps to reproduce
1. enable ingress and use the default values

**Comment by jillianwilson** [comment]
Thank you for raising this issue, I've logged this internally to be looked into further.
