### ISSUE TITLE
consider using github pages instead of tgz in the repo

### ISSUE THREAD

**Issue by mdaniel** [1Password/connect-helm-charts#15]
# What

Please consider using github pages to host the `index.yaml` and `tgz` files that comprise a helm release, instead of committing binary blobs into the git repo

# Why

Git is not well suited for hosting binary artifacts, and committing a tgz for each release will cause the repo to grow without bound (short of using some repo surgery commands to expunge old artifacts)

# How

Take for example the kubernetes ingress-nginx repo:
https://github.com/kubernetes/ingress-nginx/blob/helm-chart-3.29.0/.github/workflows/helm.yaml although I'm sure there are others, that's just the most famous one that sprang to mind which uses this pattern

One can see the repo patterns [in their install instructions](https://github.com/kubernetes/ingress-nginx/blob/helm-chart-3.29.0/docs/deploy/index.md#using-helm)

**Comment by billimek** [comment]
The [helm chart releaser action](https://github.com/helm/chart-releaser-action) as well as the [chart tester action](https://github.com/helm/chart-testing-action) are two github actions-based test and deployment patterns used by a lot of helm chart repo owners today.

It may be a good idea to at least explore or investigate this as a quick solution to achieving the concept of leveraging github pages to publish helm chart releases.  There is even a [demo repo](https://github.com/helm/charts-repo-actions-demo) showing how the actions work together.
