### ISSUE TITLE
Chart is broken and unusable

### ISSUE THREAD

**Issue by rauanmayemir** [1Password/connect-helm-charts#167]
What a nightmare, this chart is absolutely broken and unusable. I had to drop the chart and roll my own deployment.

One's helm chart is a good indicator of quality and commitment. Suggesting people use this for handling secrets and not giving a way to do stuff as basic as pointing to an existing credentials secret is just ridiculous.

Having to install this and depend on it for something as crucial as credentials and secrets is truly worrisome.

Mind you, I am not being an entitled asshole, I'm trying to use something I am paying for. Paying as business, not a proverbial cup of coffee per month kind of paying.

**Comment by Tipsmark** [comment]
ingress bit is particularly broken - I'll also have to either create a new chart or create some make-shift ingress resources on the side.

**Comment by edif2008** [comment]
Hey @rauanmayemir and @Tipsmark ! 👋 

I am sorry to hear that your experience with the Helm charts we provide didn't go as smooth as you've wanted.

Firstly, we wanted to share that when it comes to ingress, the charts work as expected based on #179. 

We really appreciate your time and effort that you have already put into trying to use these Helm charts. If you have some additional time to spare, could you provide additional details about your use case in which you want to use the helm chart and the challenges that you're facing? This will help us better understand what's missing in the current version of it and how we can improve it.

What would be useful for you to provide:
- Example snippets on how the Helm chart configuration would look like when pointing to existing credentials secrets.
- Example snippets on configuring the ingress that do not work with the Helm charts we provide. 
- Explanation on the use case and the desired goal.
- Mention any workarounds if there are any. 

Thank you! 😄

**Comment by edif2008** [comment]
Closing this as it hasn't received a reply for a while.

In the meantime, we will look into the existing bugs and issues opened and improve the Helm charts by addressing those. We will update our progress on the specific tickets. Feel free to re-open if needed and provide specific use cases challenges you're facing.
