### ISSUE TITLE
connect operator deployment fails

### ISSUE THREAD

**Issue by mmarkell** [1Password/connect-helm-charts#17]
I got this error:
```bash
Warning   FailedCreate       \
 replicaset/onepassword-connect-operator-95f9f56b7   \
Error creating: pods "onepassword-connect-operator-95f9f56b7-" \
is forbidden: error looking up service account default/onepassword-connect-operator: serviceaccount \
 "onepassword-connect-operator" not found
```

**Comment by billimek** [comment]
@mmarkell I experienced the same thing and resolved it by making sure that the `watchNamespace` chart value contained the namespace whee I was deploying the chart (and also with what the `namespace` chart value is set to).

**Comment by mmarkell** [comment]
Hi @billimek, thanks for the suggestion. I'm pretty new to helm, so don't think I quite understand. 
I tried to pass `watchNamespace` by adding an argument to the `helm install` command via: 
`--set operator.watchNamespace=default`
But that through an error 
```
Error: template: connect/templates/operator-deployment.yaml:25:24: executing "connect/templates/operator-deployment.yaml" at <include "helm-toolkit.utils.joinListWithComma" .Values.operator.watchNamespace>: error calling include: template: connect/templates/_helpers.tpl:39:20: executing "helm-toolkit.utils.joinListWithComma" at <.>: range can't iterate over default
```
Do you have any suggestion on how to try this?

**Comment by mmarkell** [comment]
So it seems like 
`--set namespace=default` is correct, syntax, but I'm still seeing the same end result error 😢

**Comment by mmarkell** [comment]
<img width="895" alt="Screen Shot 2021-04-14 at 9 34 32 AM" src="https://user-images.githubusercontent.com/10891675/114768489-9f1f7100-9d04-11eb-9df7-8b0310a2fccc.png">
Some more detail on the error

**Comment by florisvdg** [comment]
@mmarkell The issue is, like @billimek already pointed out, that `watchNamespace` has to match `namespace`. You'd have to set this manually using `--set operator.watchNamespace={your-namespace}` (note the curly braces syntax, because it's a list of namespaces).

In #18 `watchNamespace` defaults to `namespace`, so you won't have to set it manually anymore, unless you want it to watch multiple namespaces.

**Comment by mmarkell** [comment]
Hi @florisvdg , thanks for the suggestion. Unfortunately, it did not work for me. I am still getting the same error after passing
`--set operator.watchNamespace={default}` to the helm install command:
<img width="874" alt="Screen Shot 2021-04-15 at 6 08 27 AM" src="https://user-images.githubusercontent.com/10891675/114901922-ff6bec80-9db0-11eb-80f8-f3054c2c81a1.png">
