### ISSUE TITLE
helm uninstall does not remove deployment

### ISSUE THREAD

**Issue by marwan4711** [1Password/connect-helm-charts#173]
### Your environment

Chart Version: 1.14.0

Helm Version: 3.12.1

Kubernetes Version: 1.27.4

## What happened?
Please see https://1password.community/discussion/142169/helm-uninstall-does-not-remove-deployment

## What did you expect to happen?
Please see https://1password.community/discussion/142169/helm-uninstall-does-not-remove-deployment

**Comment by marwan4711** [comment]
Seems to be a known issue since 2021 (https://github.com/1Password/onepassword-operator/issues/55).

**Comment by volodymyrZotov** [comment]
Could not fix it on the 1Password Operator side. See the comment for more context https://github.com/1Password/onepassword-operator/issues/55#issuecomment-1924683424
