### ISSUE TITLE
Add ability to set Priority Class Name

### ISSUE THREAD

**Issue by jonas-zipprick** [1Password/connect-helm-charts#201]
### Summary
Add ability to set priorityClassName of the connect-deployment through helm-chart values

### Use cases
- 1password-connect is a critical service to some users and needs to have a high priority-class

### Proposed solution
Add optional value `connect.priorityClassName` that ends up in `connect-deployment.yaml`

### Is there a workaround to accomplish this today?
Currently the connect-pods will use the default priority class. So you can raise that for the entire namespace.

### References & Prior Work

* Grafana: https://github.com/grafana/agent/pull/3136

**Comment by dustin-ruetz** [comment]
Hi @jonas-zipprick :wave: Thanks for your interest in our Connect helm charts and for filing this issue, and thank you for linking to the `grafana/agent` PR as an example implementation as well.

Our team doesn’t currently have enough available bandwidth to prioritize this feature, but with that being said we’re always open to PRs if people are interested in making open source contributions to our repos. Earlier this year we modernized our [CONTRIBUTING.md](https://github.com/1Password/connect-helm-charts/blob/main/CONTRIBUTING.md) file as a starting point to help guide external contributors who are interesting in adding new features, fixing bugs, etc. If you’re interested in contributing and have the time to make a PR to add this feature then we’d be happy to review it.
