### ISSUE TITLE
Error installing helm-charts - is invalid: spec.ports[0].nodePort: Invalid value: 31080: provided port is already allocated

### ISSUE THREAD

**Issue by mikeywaites** [1Password/connect-helm-charts#22]
Hey

Been testing out the new onepassword-connect k8s operator.  Firstly, what a fantastic ideas - Our team are really keen to get this going.

Our architecture has several isolated namespaces inside a single gke cluster so our plan was to set up 1password connect and operator inside of each namespace.  

Trying to install this into a single namespace `dev` initially results in an error.  

```
helm repo add 1password https://raw.githubusercontent.com/1Password/connect-helm-charts/main

helm upgrade --install connect 1password/connect --namespace=dev --set-file connect.credentials=$SERVICES_BASE_PATH/gke-1password-dev-credentials.json --set operator.create=true --set operator.token.name=gke-1password-dev-access-token --set operator.token.value=REDACTED --set namespace=dev
```

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
"1password" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "soluto" chart repository
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "1password" chart repository
...Successfully got an update from the "stable" chart repository
...Unable to get an update from the "chartmuseum" chart repository (https://chartmuseum-gke.vizibl.co):
        Get "https://chartmuseum-gke.vizibl.co/index.yaml": context deadline exceeded
Update Complete. ⎈Happy Helming!⎈
Release "connect" does not exist. Installing it now.
Error: Service "onepassword-connect" is invalid: spec.ports[0].nodePort: Invalid value: 31080: provided port is already allocated
```

**Error: Service "onepassword-connect" is invalid: spec.ports[0].nodePort: Invalid value: 31080: provided port is already allocated**

Hope someone can help us resolve this issue.  Also, if there's any advice on how best to manage this architecture where there's  an instance of 1password connect per namespace, that would be greatly appreciated.

**Comment by jpcoenen** [comment]
Hi there :wave: 

It seems you have run into the NodePort being a fixed value. I have just merged a fix to address this so Kubernetes uses an available port. We plan on releasing a new version of the Chart later today or at latest tomorrow. 

Let me know if that fixes your problem!

**Comment by mikeywaites** [comment]
Hey Thanks for getting back to me and for addressing the issue.

I will eagerly await the release so that I can try out the fix.  I will let you know either way.
