### ISSUE TITLE
Update securityContext to use volume permission and ownership change policy

### ISSUE THREAD

**Issue by thatguygriff** [1Password/connect-helm-charts#26]
Currently we use an `initContainer` to correct the permissions on volume mounts to be accessible by reduced privilege user accounts. Starting with Kubernetes 1.20+ there is a [beta feature to configure volume permissions and perform ownership changes](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods). 

We should update the chart to support this feature and replace the initContainer flow with it.

**Comment by jpcoenen** [comment]
Yes, using `fsGroup` would be much more cleaner! 

I think we do not even need the experimental `fsGroupChangePolicy` feature. If I understand it correclty, it's only needed if you mount a volume that already contains data that is owned by another group and need it to be `chown`'ed. In our case, we have an empty volume, so I _guess_ setting `fsGroup` only would do the trick.

**Comment by thatguygriff** [comment]
Unfortunately both `fsGroup and `fsGroupChangePolicy` are 1.20+ only. I almost included them in a previous PR but tested on a 1.19 cluster and caught myself

**Comment by jpcoenen** [comment]
The `initContainer` has been removed in #80. So closing this issue.
