### ISSUE TITLE
Implement liveness/readiness probes

### ISSUE THREAD

**Issue by franklouwers** [1Password/connect-helm-charts#47]
### Summary
The current chart doesn't have liveness/readiness probes. This means Kubernetes will only restart the pod if one of the pid-1 processes in the container crashes or exists.

### Use cases
To adhere to Best Current Practices, Kubernetes should detect and act when the service is misbehaving

### Proposed solution
- Implement liveness/readiness probes, maybe based on the /health endpoint?
- Maybe also allow a restart if the service hasn't synced to the main 1Password.com service for 24 hours?

### Is there a workaround to accomplish this today?
No, unless the pod would implement that internally? Unable to verify due to lack of documentation

### References & Prior Work
Probes are BCP and have been implemented by most other commonly used charts in the K8S ecosystem :)

**Comment by mcmarkj** [comment]
I've opened https://github.com/1Password/connect-helm-charts/pull/50 for this, however, the Operator doesn't appear to have the standard /health or /heartbeat endpoints so I've not added it for the Operator.
