### ISSUE TITLE
Deploy Operator independly of Connect

### ISSUE THREAD

**Issue by franklouwers** [1Password/connect-helm-charts#48]
### Summary
Support deploying the Operator independently of the Connect.

### Use cases

Currently, this chart only supports deploying the `operator` next to the `connect` component. If a user has multiple Kubernetes clusters, or has deployed 1Password Connect outside of Kubernetes, they currently can't use this chart.

### Proposed solution

- allow an option to enable / disable the connect component
- allow a user to override the connect url in the operator deployment template.

### Is there a workaround to accomplish this today?
The Operator repo has yaml files, but no chart.

### References & Prior Work

**Comment by edif2008** [comment]
Hey.
Thank you for your suggestion. I can definitely see having only the Operator in the chart come in handy when Connect is deployed somewhere else.
We will look into potentially adding this in the future.

**Comment by alexlanz** [comment]
Hi, is there an update on this issue? It would be really nice also for us to have the possibility to install the operator and the connect server independently.

**Comment by ag-adampike** [comment]
This was addressed in #126 and should be included in the upcoming v1.11.0 release when #145 is merged.
