### ISSUE TITLE
tolerations in helm-templates

### ISSUE THREAD

**Issue by rowa78** [1Password/connect-helm-charts#63]
### Summary
I have nodes with some taints. Therefore i want to specify tolerations for the deployements. In this helmchart, i can't set those tolerations.

### Use cases
I have a separate worker. The normal workload should not be deployed there. So i tainted the node. But i want the connect-deployment on this node.

### Proposed solution
add tolerations to the helm-chart-templates. I'll prepare an PR for this.

**Comment by insider89** [comment]
Can someone review PR?
