### ISSUE TITLE
Please release a new helm chart version, 1.4.0 is currently 3 months stale

### ISSUE THREAD

**Issue by lhriley** [1Password/connect-helm-charts#71]
### Your environment

Chart Version: 1.4.0
Helm Version: 3.6.3
Kubernetes Version:  1.2.0

## What happened?
The current release of the helm chart contains several issues that have since been resolved and merged to `main`. 

## What did you expect to happen?
Regular releases of the helm chart occur to eliminate known, fixed issues and provide new features.

## Steps to reproduce
1. `helm repo add onepassword-connect https://1password.github.io/connect-helm-charts`
2. `helm search repo onepassword-connect`
3. Observe that the last release is version 1.4.0
4. Observe that the tag for 1.4.0 in github shows the latest commit was merged in June 2021: https://github.com/1Password/connect-helm-charts/commits/connect-1.4.0

## Notes & Logs
This is a particular issue for me as `main` contains changes that allow the `operator` to work across namespaces.

**Comment by pascallap** [comment]
Current release 1.4.0 doesn't support multinamespace for the operator.
It is missing the clusterrolebinding.

Please release a new version including this.

**Comment by edif2008** [comment]
Hey.
Great news. We released [1.5.0](https://github.com/1Password/connect-helm-charts/releases/tag/connect-1.5.0), which includes the clusterrolebinding compatibility, as well as watching all namespaces by default.

**Comment by verkaufer** [comment]
Closing as resolved now that 1.5.0 is out. Thank you for your patience while we got this release out!
