### ISSUE TITLE
loadBalancerIP for service

### ISSUE THREAD

**Issue by maxisam** [1Password/connect-helm-charts#88]
### Summary

There is no loadBalancerIP field for the service.

### Use cases

We want to use service type as loadbalancer

### Proposed solution

add loadBalancerIP field

### References & Prior Work

* 
*

**Comment by jillianwilson** [comment]
Hi there! Great idea, we will look into adding this for a future release.

**Comment by klaus385** [comment]
@maxisam just fyi my PR got merged in and should help satisfy this issue for you.
